language: node_js
node_js:
  - "stable"
sudo: false
install: true
script:
  - yarn install
  - yarn build
  - yarn test --no-cache
  - yarn coveralls
cache:
  yarn: true
  directories:
    - node_modules
