name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.0
      with: 
        node-version: 12.x

    - name: Install dependences
      run: yarn
      
    - name: Build
      run: yarn build
      
    - name: Tests
      run: yarn test --no-cache
    
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }
    
    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key:  ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/gobarber-api"

    - name: Install dependences on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key:  ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/gobarber-api
          yarn
          
    - name: Run migrations on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key:  ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/gobarber-api
          ./node_modules/.bin/typeorm migration:run
          
    - name: Start Node.js on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key:  ${{ secrets.SSH_KEY }}
        script: 
          pm2 restart gobarber-api
